### ISSUE TITLE
Pretrained model url link broken?

### ISSUE THREAD

**Issue by oalieno** [CUMLSec/trex#3]
This link [pretrained weight parameters](https://drive.google.com/file/d/1eVnlqUvii6tKC1LKYL0dQ_x-4d0LrgA6/view?usp=sharing) seems to be broken.

**Comment by peikexin9** [comment]
Sorry @oalieno, it was accidentally deleted. Just fixed.

**Comment by oalieno** [comment]
Thanks for the update.
